import React from 'react';
import ReactDOM from 'react-dom/client';
import { RouterProvider, createRouter } from '@tanstack/react-router';
import { QueryClient, QueryClientProvider, onlineManager } from '@tanstack/react-query';
import { persistQueryClient } from '@tanstack/react-query-persist-client';
import { createAsyncStoragePersister } from '@tanstack/query-async-storage-persister';
import { get, set, del } from 'idb-keyval';
import { AlertTriangle } from 'lucide-react';

// Route tree generated by TanStack Router
import { routeTree } from './routeTree.gen';
import { supabase } from './lib/supabase';
import './index.css';

// ------------------------------------------------------------------
// 1. CORE ENGINE UPGRADE (Strict Offline-First & 401 Interception)
// ------------------------------------------------------------------
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      gcTime: 1000 * 60 * 60 * 24 * 14, // 14 days
      staleTime: 1000 * 60 * 5, // 5 minutes
      retry: 3,
      refetchOnWindowFocus: true,
      networkMode: 'offlineFirst',
    },
    mutations: {
      networkMode: 'offlineFirst',
      // ENTERPRISE FIX: Intercept 401 Auth errors to prevent queue deletion
      retry: (failureCount, error: any) => {
        const isAuthError = error?.status === 401 || error?.code === 'PGRST301' || error?.message?.includes('JWT');
        
        if (isAuthError) {
          console.warn('[Sync Engine] Auth token expired during offline sync. Attempting GoTrue refresh...');
          supabase.auth.refreshSession().then(({ data }) => {
            if (data?.session) {
              console.log('[Sync Engine] Session securely restored. Forcing mutation retry.');
            }
          });
          return true; // Force TanStack to retry the payload with the new token
        }
        
        // Default behavior: retry standard network errors up to 3 times
        return failureCount < 3;
      },
      retryDelay: (attemptIndex) => Math.min(1000 * 2 ** attemptIndex, 30000),
    }
  },
});

// ------------------------------------------------------------------
// 2. ASYNC STORAGE ADAPTER (IndexedDB)
// ------------------------------------------------------------------
const idbStorage = {
  getItem: async (key: string) => {
    const val = await get(key);
    return val === undefined ? null : val;
  },
  setItem: async (key: string, value: any) => await set(key, value),
  removeItem: async (key: string) => await del(key),
};

const persister = createAsyncStoragePersister({
  storage: idbStorage as any,
});

// ------------------------------------------------------------------
// 3. EXPLICIT CACHE DEHYDRATION (With iOS RAM-Only Fallback)
// ------------------------------------------------------------------
// Detect iOS devices (including iPads masquerading as Macs via Desktop Mode)
const isIOS = /iPad|iPhone|iPod/.test(navigator.userAgent) || 
  (navigator.platform === 'MacIntel' && navigator.maxTouchPoints > 1);

// Only persist the cache to the hard drive (IndexedDB) if NOT on iOS
if (!isIOS) {
  console.log('[Sync Engine] Non-iOS device detected. Enabling 14-day disk persistence.');
  persistQueryClient({
    queryClient,
    persister,
    maxAge: 1000 * 60 * 60 * 24 * 14,
    buster: 'v1.0.6',
    dehydrateOptions: {
      shouldDehydrateQuery: (query) => query.state.status === 'success',
      shouldDehydrateMutation: (mutation) => mutation.state.isPaused, 
    },
  });
} else {
  console.warn('[Sync Engine] iOS Device detected. Operating in Online-Only RAM mode to prevent WebKit memory purges.');
}

// ------------------------------------------------------------------
// 4. OFFLINE RECOVERY HANDLERS
// ------------------------------------------------------------------
queryClient.resumePausedMutations();

onlineManager.subscribe((isOnline) => {
  if (isOnline) {
    console.log('[Sync Engine] Network restored. Firing offline mutation queue.');
    queryClient.resumePausedMutations();
  }
});

// ------------------------------------------------------------------
// 5. ROUTER & GLOBAL ERROR BOUNDARIES
// ------------------------------------------------------------------
const router = createRouter({
  routeTree,
  context: { queryClient },
  defaultPreload: 'intent',
  
  defaultNotFoundComponent: () => (
    <div className="h-screen w-screen flex flex-col items-center justify-center bg-slate-50 text-slate-900">
      <h1 className="text-4xl font-black mb-4">404</h1>
      <p className="font-bold uppercase tracking-widest text-sm mb-8 text-slate-500">System Route Not Found</p>
      <a href="/" className="px-6 py-3 bg-emerald-600 text-white rounded-xl font-bold uppercase text-xs hover:bg-emerald-500 transition-colors shadow-sm">
        Return to Dashboard
      </a>
    </div>
  ),

  defaultErrorComponent: ({ error, reset }) => (
    <div className="h-screen w-screen flex flex-col items-center justify-center bg-slate-50 p-6">
      <div className="bg-white p-8 rounded-2xl shadow-xl max-w-lg w-full border border-rose-200 flex flex-col items-center text-center">
        <div className="w-16 h-16 bg-rose-100 rounded-full flex items-center justify-center mb-6">
          <AlertTriangle className="text-rose-600" size={32} />
        </div>
        <h2 className="text-xl font-black text-slate-900 uppercase tracking-tight mb-2">System Exception</h2>
        <p className="text-sm font-medium text-slate-500 mb-6 bg-slate-50 p-4 rounded-xl border border-slate-100 w-full overflow-x-auto text-left">
          {error.message || 'An unknown architectural error occurred.'}
        </p>
        <button 
          onClick={() => {
            queryClient.clear();
            reset();
          }}
          className="w-full py-3 bg-slate-900 text-white rounded-xl font-bold uppercase tracking-widest text-xs hover:bg-slate-800 transition-all shadow-md"
        >
          Flush Cache & Recover
        </button>
      </div>
    </div>
  ),
});

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
    </QueryClientProvider>
  </React.StrictMode>
);